name: Film workflow project

on:
  workflow_run:
    workflows: ["Tests 14 sprint"]
    branches: [review-3]
    types:
      - completed

jobs:
  build_and_push_to_docker_hub:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Push Docker images to Docker GitHub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Push to Docker Hub (backend)
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_LABEL }}/film_backend:latest
          context: backend/
      - name: Push to Docker Hub (frontend)
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKER_LABEL }}/film_frontend:latest
          context: frontend/
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
      - name: executing remote ssh commands to deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}
          script: |
            sudo docker pull ${{ secrets.DOCKER_LABEL }}/film_backend:latest
            sudo docker pull ${{ secrets.DOCKER_LABEL }}/film_frontend:latest
            sudo docker-compose stop
            sudo docker-compose rm backend
            sudo docker-compose rm frontend
            rm .env
            touch .env
            echo DATABASE_URL=${{ secrets.DATABASE_URL }} >> .env
            echo DATABASE_DRIVER=${{ secrets.DATABASE_DRIVER }} >> .env
            echo DATABASE_HOST=${{ secrets.DATABASE_HOST }} >> .env
            echo DATABASE_PORT=${{ secrets.DATABASE_PORT }} >> .env
            echo DATABASE_NAME=${{ secrets.DATABASE_NAME }} >> .env
            echo DATABASE_USERNAME=${{ secrets.DATABASE_USERNAME }} >> .env
            echo DATABASE_PASSWORD=${{ secrets.DATABASE_PASSWORD }} >> .env
            echo PGADMIN_DEFAULT_EMAIL=${{ secrets.PGADMIN_DEFAULT_EMAIL }} >> .env
            echo PGADMIN_DEFAULT_PASSWORD=${{ secrets.PGADMIN_DEFAULT_PASSWORD }} >> .env
            echo LOGGER_TYPE=${{ secrets.LOGGER_TYPE }} >> .env
            echo VITE_API_URL=${{ secrets.VITE_API_URL }} >> .env
            echo VITE_CDN_URL=${{ secrets.VITE_CDN_URL }} >> .env
            sudo docker-compose up -d --build
            sudo docker-compose exec -T npm run migrate:up
